In [1]:
import numpy as np 

In [2]:
# creation of numpy array

x= np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# shape and size 

print(x.shape) # total no of elements
print(x.size)  #  dimensions 
print(x.ndim)  # num of dimensions 

(5,)
5
1


In [4]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.shape)
print(x2d.size)
print(x2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [5]:
x25 = np.random.randint(1,100, (5,5))
print(x25)

[[32 76  9 13 29]
 [53 64 60 66 79]
 [ 3 38 83  1 36]
 [16 40 41 57 20]
 [18 30 83 77 49]]


In [6]:
xseq1 = np.arrange(1, 101, 4)
print("1D MATRIX")
print(xseq1)
print("=>1D MATRIX RESHAPED TO 2D")




AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
xseq2 = np.linespace(1, 101, 4)
print(xseq2,size,"elements")
print("=>1D MATRIX")
print(xseq2)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))
print("=>1D MATRIX RESHAPED TO 3D")
print(xseq2.reshape(5,5,2))


AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
np.ones((10,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stats
- methods 

In [ ]:
x25 

array([[86, 72, 20, 10, 73],
       [76, 17, 57, 88, 27],
       [30, 77,  4, 68, 10],
       [12, 83, 48, 37, 60],
       [52, 41, 66, 11, 37]])

In [ ]:
# last row 
print(x25[-1])

[52 41 66 11 37]


In [ ]:
# last row 
print(x25[-1])

[52 41 66 11 37]


In [ ]:
print(x25[0,1]) # same as print(x25[0][1])

72


In [ ]:
# 1st coloum 

print(x25[:,0])

# 2nd coloum 
print(x25[:,1])

#3rd coloum 
print(x25[:,-1])


[86 76 30 12 52]
[72 17 77 83 41]
[73 27 10 60 37]


In [ ]:
# coloum 0 and 1 idxs
print(x25[:,[0,1]])

[[86 72]
 [76 17]
 [30 77]
 [12 83]
 [52 41]]


In [ ]:
# coloum 0,1,2 idxs 
print(x25[:, [0,1,2]])
# same thing as above 
print(x25[:, :3])

[[86 72 20]
 [76 17 57]
 [30 77  4]
 [12 83 48]
 [52 41 66]]
[[86 72 20]
 [76 17 57]
 [30 77  4]
 [12 83 48]
 [52 41 66]]


In [ ]:
x25

array([[86, 72, 20, 10, 73],
       [76, 17, 57, 88, 27],
       [30, 77,  4, 68, 10],
       [12, 83, 48, 37, 60],
       [52, 41, 66, 11, 37]])

In [ ]:
for i in x25:
    print(i)

[86 72 20 10 73]
[76 17 57 88 27]
[30 77  4 68 10]
[12 83 48 37 60]
[52 41 66 11 37]


In [ ]:
for i in x25:
    for j in i:
        if j >= 20:
            print(j)


86
72
20
73
76
57
88
27
30
77
68
83
48
37
60
52
41
66
37


In [ ]:
x25 <= 20 # boolean filter 

array([[False, False,  True,  True, False],
       [False,  True, False, False, False],
       [False, False,  True, False,  True],
       [ True, False, False, False, False],
       [False, False, False,  True, False]])

In [ ]:
x25[x25 <=20]

array([20, 10, 17,  4, 10, 12, 11])

In [ ]:
x25[x25 >=20]

array([86, 72, 20, 73, 76, 57, 88, 27, 30, 77, 68, 83, 48, 37, 60, 52, 41,
       66, 37])

In [ ]:
[(x25 > 20) & (x25 < 70) ]

[array([[False, False, False, False, False],
        [False, False,  True, False,  True],
        [ True, False, False,  True, False],
        [False, False,  True,  True,  True],
        [ True,  True,  True, False,  True]])]

In [ ]:
np.append(x25, [1,2,3,4,5])

array([86, 72, 20, 10, 73, 76, 17, 57, 88, 27, 30, 77,  4, 68, 10, 12, 83,
       48, 37, 60, 52, 41, 66, 11, 37,  1,  2,  3,  4,  5])

In [ ]:
np.append(x25, np.array([[1,2,3,5,6]]), axis=0)

array([[86, 72, 20, 10, 73],
       [76, 17, 57, 88, 27],
       [30, 77,  4, 68, 10],
       [12, 83, 48, 37, 60],
       [52, 41, 66, 11, 37],
       [ 1,  2,  3,  5,  6]])

In [ ]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (2,3))

In [ ]:
print(a.shape)
print(a.size)

(3, 2)
6


In [ ]:
a.transpose()

array([[13, 83, 55],
       [45, 74, 34]])

In [ ]:
a.T # same as transpose()

array([[13, 83, 55],
       [45, 74, 34]])

In [ ]:
print(np.hstack((a,b.T)))

[[13 45 92 56]
 [83 74 90 55]
 [55 34 41  9]]


In [ ]:
print(np.hstack((a. T,b)))

[[13 83 55 92 90 41]
 [45 74 34 56 55  9]]


In [ ]:
print(np.vstack((a,b.T)))
print(np.vstack((a.T,b)))

[[13 45]
 [83 74]
 [55 34]
 [92 56]
 [90 55]
 [41  9]]
[[13 83 55]
 [45 74 34]
 [92 90 41]
 [56 55  9]]
